# Generated by Django 4.2 on 2025-10-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='level',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
