# Generated by Django 4.2 on 2026-01-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0005_alter_pokemon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="pokemons",
            field=models.ManyToManyField(
                blank=True, related_name="trainers", to="pokedex.pokemon"
            ),
        ),
    ]
