# Generated by Django 4.2 on 2026-01-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0006_trainer_pokemons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="pokemons",
        ),
        migrations.AddField(
            model_name="trainer",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="trainer_picture/"
            ),
        ),
    ]
